package com.maktab.student.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/** A child receiving lessons. Students are deactivated, never deleted. */
@Entity
@Table(name = "student")
public class Student {

    @Id
    private UUID id;

    @Column(name = "organisation_id", nullable = false, updatable = false)
    private UUID organisationId;

    @Column(name = "first_name", nullable = false)
    private String firstName;

    @Column(name = "last_name", nullable = false)
    private String lastName;

    @Column(name = "date_of_birth", nullable = false)
    private LocalDate dateOfBirth;

    @Enumerated(EnumType.STRING)
    private Gender gender;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private StudentStatus status = StudentStatus.ACTIVE;

    @Column(name = "joined_on", nullable = false)
    private LocalDate joinedOn;

    @Column(name = "left_on")
    private LocalDate leftOn;

    private String notes;

    /** Generated by the database from the name; used only for search. */
    @Column(name = "search_name", insertable = false, updatable = false)
    private String searchName;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Version
    private long version;

    protected Student() {
    }

    public Student(UUID organisationId, String firstName, String lastName, LocalDate dateOfBirth, Gender gender,
            LocalDate joinedOn, String notes) {
        this.id = UUID.randomUUID();
        this.organisationId = organisationId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.joinedOn = joinedOn;
        this.notes = notes;
    }

    @PrePersist
    void onCreate() {
        createdAt = Instant.now();
        updatedAt = createdAt;
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = Instant.now();
    }

    public void updateDetails(String firstName, String lastName, LocalDate dateOfBirth, Gender gender,
            LocalDate joinedOn, String notes) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.joinedOn = joinedOn;
        this.notes = notes;
    }

    public void deactivate(LocalDate leftOn) {
        this.status = StudentStatus.INACTIVE;
        this.leftOn = leftOn.isBefore(joinedOn) ? joinedOn : leftOn;
    }

    public void activate() {
        this.status = StudentStatus.ACTIVE;
        this.leftOn = null;
    }

    public boolean isActive() {
        return status == StudentStatus.ACTIVE;
    }

    public UUID getId() {
        return id;
    }

    public UUID getOrganisationId() {
        return organisationId;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public Gender getGender() {
        return gender;
    }

    public StudentStatus getStatus() {
        return status;
    }

    public LocalDate getJoinedOn() {
        return joinedOn;
    }

    public LocalDate getLeftOn() {
        return leftOn;
    }

    public String getNotes() {
        return notes;
    }
}
