package com.maktab.audit.domain;

/** Actions written to the audit log. Stored as text, so new values need no migration. */
public enum AuditAction {
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    USER_CREATED,
    USER_UPDATED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    USER_ROLES_CHANGED,
    USER_PERMISSIONS_CHANGED,
    STUDENT_CREATED,
    STUDENT_UPDATED,
    STUDENT_ACTIVATED,
    STUDENT_DEACTIVATED,
    STUDENT_PARENTS_CHANGED,
    ENROLLMENT_STARTED,
    ENROLLMENT_ENDED,
    PARENT_CREATED,
    PARENT_UPDATED,
    CURRICULUM_LEVEL_CREATED,
    CLASS_CREATED,
    CLASS_UPDATED,
    CLASS_TEACHERS_CHANGED,
    CLASS_SCHEDULE_CHANGED,
    CURRICULUM_PERIOD_CREATED,
    CURRICULUM_PERIOD_UPDATED,
    LESSON_OPENED,
    LESSON_UPDATED,
    ATTENDANCE_RECORDED
}
